import Foundation

enum Texts {
    static func get(_ key: String, _ language: String) -> String { language == "ko" ? (ko[key] ?? key) : key }
    static let ko: [String: String] = [
        "CKPool connection test":"CKPool 연결 테스트", "Test connection":"연결 테스트", "Cancel":"취소",
        "Server connection":"서버 접속", "Address authorization":"주소 인증", "Mining work received":"채굴 작업 수신",
        "Connection test passed":"연결 테스트 성공", "Connection test cancelled":"연결 테스트 취소됨",
        "Timed out connecting to CKPool":"CKPool 서버 접속 시간 초과",
        "Timed out waiting for address authorization":"주소 인증 응답 시간 초과",
        "Timed out waiting for mining work":"채굴 작업 수신 시간 초과",
        "Tests the address above without saving or mining. Existing mining continues. Your public address is sent to CKPool; the test closes within 20 seconds. Share acceptance is not tested.":"위 주소로 저장·채굴 없이 확인합니다. 기존 채굴은 계속됩니다. 공개 주소가 CKPool에 전달되며 20초 이내에 테스트 연결을 닫습니다. share 승인은 검사하지 않습니다.",
        "Edit":"편집", "Undo":"실행 취소", "Redo":"다시 실행", "Cut":"잘라내기",
        "Copy":"복사", "Paste":"붙여넣기", "Select All":"전체 선택",
        "Overview":"개요", "Activity":"활동 로그", "Blocks":"블록 기록", "Settings":"설정",
        "Your tiny Bitcoin miner.":"맥 위의 작은 비트코인 광부.", "Open Stoneaxe":"Stoneaxe 열기",
        "Pause":"일시정지", "Resume":"다시 시작", "Quit Stoneaxe":"Stoneaxe 종료",
        "Starting":"시작하는 중", "Checking GPU":"GPU 검증 중", "Connected":"연결됨",
        "Disconnected":"연결 안 됨", "Connecting":"연결 중", "Reconnecting":"다시 연결 중",
        "GPU response timed out":"GPU 응답 시간 초과", "GPU busy · yielding":"GPU 작업 지연 · 잠시 양보",
        "Restart Stoneaxe to retry the GPU":"GPU 재시도는 Stoneaxe를 재시작해 주세요",
        "Set your Bitcoin address":"비트코인 주소를 설정해 주세요", "Paused":"일시정지",
        "Sleeping":"잠자기", "On battery":"배터리 사용 중", "Cooling down":"열 식히는 중",
        "Reducing heat":"발열로 강도 감소", "Away · mining gently":"자리 비움 · 여유롭게 채굴",
        "In use · mining lightly":"사용 중 · 가볍게 채굴", "Waiting for pool work":"풀 작업 기다리는 중",
        "Mining stopped after error":"오류로 채굴 중지", "Hashrate":"해시레이트", "Last 60 seconds":"최근 60초",
        "Session":"이번 실행", "Today":"오늘", "All time":"전체", "Mining time":"채굴 시간",
        "Average hashrate":"평균 해시레이트", "Total hashes":"누적 해시 계산", "Best difficulty":"최고 난이도",
        "Shares accepted":"승인된 share", "Shares submitted":"제출한 share", "Shares rejected":"거절된 share",
        "Unknown outcome":"결과 미확인", "Last accepted":"마지막 승인", "No shares yet":"아직 없음",
        "Paused time":"대기 시간", "Cooling time":"발열 대기 시간", "GPU compute time":"GPU 계산 시간",
        "Scheduling budget":"채굴 시간 예산", "Last GPU batch":"최근 GPU 작업", "Memory footprint":"메모리 사용량",
        "Budget controls compute time and rest intervals; it is not total GPU utilization.":"작업 시간과 쉬는 간격을 조절하는 예산입니다. 전체 GPU 사용률이 아닙니다.",
        "Accepted shares are work reports, not Bitcoin payouts.":"승인된 share는 작업 보고이며 비트코인 지급을 뜻하지 않습니다.",
        "No activity yet":"아직 활동이 없습니다", "All levels":"모든 수준", "Errors & warnings":"오류·경고",
        "Search logs":"로그 검색", "Show log files":"로그 파일 보기", "Export statistics":"통계 내보내기",
        "Recent 300 events. Rotating files retain up to 4 MB. Disk logs use English for diagnostics.":"최근 300개 이벤트. 로그 파일은 최대 약 4MB로 순환 저장합니다. 파일에는 진단용 영문 로그를 기록합니다.",
        "No blocks found yet":"아직 발견한 블록이 없습니다",
        "Every hash is another try. Keep your expectations small and your pickaxe moving.":"해시 한 번에 도전 한 번. 작은 기대와 함께 곡괭이를 움직여 보세요.",
        "Candidate":"블록 후보", "In main chain":"메인 체인 포함", "Not in main chain":"메인 체인 미포함",
        "Confirmations":"확인 수", "Pool accepted":"풀 승인", "Pending":"대기 중", "Yes":"예", "No":"아니요",
        "View block":"블록 보기", "Copy hash":"해시 복사", "Found":"발견 시각", "Payout address":"지급 주소",
        "Block candidates are verified against mempool.space. Verification runs while Stoneaxe is open, for up to 7 days or 100 confirmations. Explorer failures leave the result pending.":"블록 후보는 mempool.space에서 확인합니다. 앱 실행 중 최대 7일 또는 100회 확인까지 추적하며, 조회 실패는 대기 상태로 남습니다.",
        "Bitcoin receiving address":"비트코인 수신 주소", "Paste your Sparrow receiving address":"Sparrow 수신 주소 붙여넣기",
        "Only a public mainnet receiving address. Never enter a seed phrase or private key.":"메인넷 공개 수신 주소만 입력하세요. 시드 문구나 개인 키는 필요하지 않습니다.",
        "Enable automatic mining":"자동 채굴 활성화", "Allow mining on battery":"배터리에서도 채굴",
        "Launch at login":"로그인 시 실행", "Language":"언어", "Behaviour":"동작",
        "While using your Mac":"맥 사용 중", "While away":"자리 비움", "Consider away after":"자리 비움 기준",
        "minutes":"분", "Notifications":"알림", "Block discoveries & confirmations":"블록 발견·포함 확인",
        "Accepted shares (not rewards)":"share 승인 (보상 아님)", "Allow notifications":"알림 허용",
        "Notifications allowed":"알림 허용됨", "Notifications not allowed":"알림이 허용되지 않음",
        "Open notification settings":"알림 설정 열기", "Network verification":"네트워크 확인",
        "Verify block candidates with mempool.space":"mempool.space로 블록 후보 확인",
        "Only when a block candidate is found, its hash and your IP are sent to mempool.space. Your seed and keys are never needed. CKPool receives your payout address over Stratum V1 (unencrypted).":"블록 후보 발견 시에만 해시와 접속 IP가 mempool.space에 전달됩니다. 시드와 키는 사용하지 않습니다. CKPool에는 Stratum V1(암호화되지 않은 연결)으로 지급 주소가 전달됩니다.",
        "Save & apply":"저장 및 적용", "Saved":"저장됨", "Invalid mainnet Bitcoin address":"올바른 메인넷 비트코인 주소를 입력하세요",
        "Idle budget must be at least the active budget":"자리 비움 예산은 사용 중 예산 이상이어야 합니다",
        "Could not update login item":"로그인 항목을 변경하지 못했습니다", "Export failed":"내보내기 실패",
        "Exported":"내보내기 완료", "Retry engine":"엔진 재시도", "Open settings":"설정 열기",
        "Small work. Long odds.":"작은 곡괭이, 아주 작은 확률.", "GPU self-test passed":"GPU 자체 검증 통과",
        "Stoneaxe started":"Stoneaxe 시작", "Stoneaxe stopped":"Stoneaxe 종료",
        "Pool authorized":"풀 인증 완료", "Pool connection unavailable":"풀에 연결할 수 없음",
        "Pool connection closed":"풀 연결 끊김", "Pool timed out":"풀 응답 시간 초과",
        "Pool send failed":"풀 전송 실패", "Pool handshake timed out":"풀 초기 연결 시간 초과",
        "Pool requested reconnect":"풀에서 재연결 요청", "Wallet authorization failed":"주소 인증 실패",
        "Invalid pool message":"잘못된 풀 메시지", "Pool message too large":"풀 메시지 크기 초과",
        "Too many pending requests":"대기 요청 수 초과", "Share accepted":"share 승인",
        "Share rejected":"share 거절", "Share outcome unknown":"share 결과 미확인",
        "GPU initialization failed":"GPU 초기화 실패", "GPU execution failed":"GPU 실행 실패",
        "GPU/CPU hash mismatch":"GPU·CPU 해시 불일치", "GPU result buffer overflow":"GPU 결과 버퍼 초과",
        "Invalid mining work":"잘못된 채굴 작업", "Could not save statistics":"통계를 저장하지 못했습니다",
        "Could not write log":"로그를 저장하지 못했습니다", "Block candidate found":"블록 후보 발견",
        "Block included in main chain":"블록이 메인 체인에 포함됨", "Block left the main chain":"블록이 메인 체인에서 제외됨",
        "Stoneaxe found a block!":"Stoneaxe가 블록을 발견했습니다!", "100 block confirmations":"블록 확인 100회 도달",
        "Work accepted by CKPool. This is not a block reward.":"CKPool이 작업을 승인했습니다. 블록 보상은 아닙니다.",
        "Network confirmation pending. A share acceptance alone does not confirm a block.":"네트워크 확인 중입니다. share 승인만으로 블록 포함이 확인되지는 않습니다.",
        "The block is in the main chain. Coinbase rewards require maturity and can be affected by reorganizations.":"블록이 메인 체인에 포함되었습니다. 코인베이스 보상은 성숙 기간이 필요하며 체인 재구성의 영향을 받을 수 있습니다.",
        "The network reorganized. The block reward is not confirmed.":"체인이 재구성되었습니다. 블록 보상은 확정되지 않았습니다.",
        "Check the coinbase output in your wallet. Stoneaxe does not verify your spendable balance.":"지갑에서 코인베이스 출력을 확인하세요. Stoneaxe는 사용 가능한 잔액을 검증하지 않습니다."
    ]
}
